name: Generate documentation

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  Publish:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: "TootSDK/TootSDK"
      - name: Install jazzy
        run: |
          gem install jazzy
      - name: Jazzy version
        run: |
          jazzy -version
          type -a jazzy
      - name: Print dir
        run: |
          pwd
          ls
      - name: Regenerate docs
        run: |
          bash ./updatedocs.sh
      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
